// <auto-generated />
using System;
using Dierentuin_eindopdracht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dierentuin_eindopdracht.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20250304170430_FirstOne")]
    partial class FirstOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalCategoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Arise")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BedTime")
                        .HasColumnType("time");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FeedingTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("AnimalCategoryId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            ActivityPattern = 1,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(204936100038),
                            BedTime = new TimeSpan(639929576997),
                            DietaryClass = 4,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(24439393770),
                            Name = "Grayson",
                            Prey = "Giraffe",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 473.9013915992814,
                            Species = "Eagle",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            ActivityPattern = 2,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(17720186935),
                            BedTime = new TimeSpan(99330009689),
                            DietaryClass = 3,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(5365199963),
                            Name = "Jamal",
                            Prey = "Zebra",
                            SecurityRequirement = 1,
                            Size = 5,
                            SpaceRequirement = 296.87672797910722,
                            Species = "Wolf",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 3,
                            ActivityPattern = 1,
                            AnimalCategoryId = 5,
                            Arise = new TimeSpan(107426665803),
                            BedTime = new TimeSpan(410371992042),
                            DietaryClass = 3,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(54176958229),
                            Name = "Shawna",
                            Prey = "Giraffe",
                            SecurityRequirement = 1,
                            Size = 6,
                            SpaceRequirement = 448.47399293373985,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 4,
                            ActivityPattern = 3,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(111519569877),
                            BedTime = new TimeSpan(399521969314),
                            DietaryClass = 4,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(66083643802),
                            Name = "Lisandro",
                            Prey = "Crocodile",
                            SecurityRequirement = 1,
                            Size = 2,
                            SpaceRequirement = 82.512082873150746,
                            Species = "Eagle",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 5,
                            ActivityPattern = 2,
                            AnimalCategoryId = 4,
                            Arise = new TimeSpan(41852732775),
                            BedTime = new TimeSpan(243734136646),
                            DietaryClass = 1,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(25330644821),
                            Name = "Ian",
                            Prey = "Elephant",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 404.71676491420567,
                            Species = "Eagle",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 6,
                            ActivityPattern = 1,
                            AnimalCategoryId = 5,
                            Arise = new TimeSpan(102754421077),
                            BedTime = new TimeSpan(186054146388),
                            DietaryClass = 3,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(36385736341),
                            Name = "Thad",
                            Prey = "Lion",
                            SecurityRequirement = 1,
                            Size = 3,
                            SpaceRequirement = 468.34364081655798,
                            Species = "Giraffe",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 7,
                            ActivityPattern = 2,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(16272114422),
                            BedTime = new TimeSpan(94591060872),
                            DietaryClass = 1,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(41974582345),
                            Name = "Leon",
                            Prey = "Lion",
                            SecurityRequirement = 2,
                            Size = 6,
                            SpaceRequirement = 56.579863082887542,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 8,
                            ActivityPattern = 1,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(91478088049),
                            BedTime = new TimeSpan(315905564336),
                            DietaryClass = 3,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(22879923552),
                            Name = "Aisha",
                            Prey = "Crocodile",
                            SecurityRequirement = 1,
                            Size = 3,
                            SpaceRequirement = 285.21334405765555,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 9,
                            ActivityPattern = 1,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(10746789531),
                            BedTime = new TimeSpan(285113426103),
                            DietaryClass = 3,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(43451053517),
                            Name = "Roosevelt",
                            Prey = "Penguin",
                            SecurityRequirement = 1,
                            Size = 5,
                            SpaceRequirement = 491.68804400213435,
                            Species = "Crocodile",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 10,
                            ActivityPattern = 1,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(80826539200),
                            BedTime = new TimeSpan(167761950385),
                            DietaryClass = 3,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(51812972525),
                            Name = "Amely",
                            Prey = "Zebra",
                            SecurityRequirement = 3,
                            Size = 4,
                            SpaceRequirement = 432.04042462727074,
                            Species = "Zebra",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 11,
                            ActivityPattern = 2,
                            AnimalCategoryId = 1,
                            Arise = new TimeSpan(193345395450),
                            BedTime = new TimeSpan(191294216137),
                            DietaryClass = 2,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(70624234612),
                            Name = "Quinn",
                            Prey = "Elephant",
                            SecurityRequirement = 2,
                            Size = 3,
                            SpaceRequirement = 16.313045614544791,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 12,
                            ActivityPattern = 3,
                            AnimalCategoryId = 4,
                            Arise = new TimeSpan(99618252912),
                            BedTime = new TimeSpan(468805838904),
                            DietaryClass = 2,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(62611278876),
                            Name = "Laverna",
                            Prey = "Tiger",
                            SecurityRequirement = 3,
                            Size = 3,
                            SpaceRequirement = 223.17880367542563,
                            Species = "Giraffe",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 13,
                            ActivityPattern = 1,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(132349561310),
                            BedTime = new TimeSpan(70577464565),
                            DietaryClass = 2,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(25083270684),
                            Name = "Ona",
                            Prey = "Crocodile",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 199.41648925627419,
                            Species = "Zebra",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 14,
                            ActivityPattern = 3,
                            AnimalCategoryId = 3,
                            Arise = new TimeSpan(64352514990),
                            BedTime = new TimeSpan(622210020716),
                            DietaryClass = 4,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(3653405251),
                            Name = "Chyna",
                            Prey = "Crocodile",
                            SecurityRequirement = 2,
                            Size = 5,
                            SpaceRequirement = 411.3170782110268,
                            Species = "Wolf",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 15,
                            ActivityPattern = 2,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(129931104601),
                            BedTime = new TimeSpan(220119403796),
                            DietaryClass = 1,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(19979382051),
                            Name = "Griffin",
                            Prey = "Crocodile",
                            SecurityRequirement = 3,
                            Size = 4,
                            SpaceRequirement = 222.31171337995292,
                            Species = "Giraffe",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 16,
                            ActivityPattern = 3,
                            AnimalCategoryId = 6,
                            Arise = new TimeSpan(152857818418),
                            BedTime = new TimeSpan(683754096838),
                            DietaryClass = 2,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(3619670270),
                            Name = "Orville",
                            Prey = "Giraffe",
                            SecurityRequirement = 3,
                            Size = 5,
                            SpaceRequirement = 182.93205114683698,
                            Species = "Shark",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 17,
                            ActivityPattern = 3,
                            AnimalCategoryId = 1,
                            Arise = new TimeSpan(28083613930),
                            BedTime = new TimeSpan(289542201017),
                            DietaryClass = 2,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(57129796535),
                            Name = "Frida",
                            Prey = "Wolf",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 498.99183494923255,
                            Species = "Shark",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 18,
                            ActivityPattern = 3,
                            AnimalCategoryId = 6,
                            Arise = new TimeSpan(161271415312),
                            BedTime = new TimeSpan(770496067041),
                            DietaryClass = 3,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(9242950943),
                            Name = "Rupert",
                            Prey = "Zebra",
                            SecurityRequirement = 1,
                            Size = 5,
                            SpaceRequirement = 42.225983786501914,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 19,
                            ActivityPattern = 1,
                            AnimalCategoryId = 6,
                            Arise = new TimeSpan(165497481911),
                            BedTime = new TimeSpan(697386550897),
                            DietaryClass = 2,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(31555508833),
                            Name = "Nash",
                            Prey = "Zebra",
                            SecurityRequirement = 3,
                            Size = 4,
                            SpaceRequirement = 72.629228761712668,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 20,
                            ActivityPattern = 2,
                            AnimalCategoryId = 6,
                            Arise = new TimeSpan(73708368492),
                            BedTime = new TimeSpan(428877822405),
                            DietaryClass = 5,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(14361095182),
                            Name = "Mariane",
                            Prey = "Elephant",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 289.29339600694061,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 21,
                            ActivityPattern = 1,
                            AnimalCategoryId = 3,
                            Arise = new TimeSpan(95051427047),
                            BedTime = new TimeSpan(454837718490),
                            DietaryClass = 2,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(10821104356),
                            Name = "Arden",
                            Prey = "Eagle",
                            SecurityRequirement = 2,
                            Size = 6,
                            SpaceRequirement = 427.09427699311368,
                            Species = "Crocodile",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 22,
                            ActivityPattern = 2,
                            AnimalCategoryId = 5,
                            Arise = new TimeSpan(181584039706),
                            BedTime = new TimeSpan(746942967934),
                            DietaryClass = 1,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(69495288211),
                            Name = "Easter",
                            Prey = "Penguin",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 315.28516944743933,
                            Species = "Shark",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 23,
                            ActivityPattern = 1,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(132488325494),
                            BedTime = new TimeSpan(727653002549),
                            DietaryClass = 4,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(42345596158),
                            Name = "Victor",
                            Prey = "Wolf",
                            SecurityRequirement = 2,
                            Size = 5,
                            SpaceRequirement = 446.3634764712134,
                            Species = "Eagle",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 24,
                            ActivityPattern = 2,
                            AnimalCategoryId = 5,
                            Arise = new TimeSpan(177995547601),
                            BedTime = new TimeSpan(386270163127),
                            DietaryClass = 1,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(19631051881),
                            Name = "Fred",
                            Prey = "Eagle",
                            SecurityRequirement = 2,
                            Size = 6,
                            SpaceRequirement = 151.97761894295812,
                            Species = "Crocodile",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 25,
                            ActivityPattern = 3,
                            AnimalCategoryId = 5,
                            Arise = new TimeSpan(61080534345),
                            BedTime = new TimeSpan(715448422326),
                            DietaryClass = 3,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(6309776615),
                            Name = "Claud",
                            Prey = "Penguin",
                            SecurityRequirement = 1,
                            Size = 4,
                            SpaceRequirement = 13.287990751344706,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 26,
                            ActivityPattern = 2,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(176255972747),
                            BedTime = new TimeSpan(191489009052),
                            DietaryClass = 3,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(45376925020),
                            Name = "Oceane",
                            Prey = "Zebra",
                            SecurityRequirement = 2,
                            Size = 5,
                            SpaceRequirement = 300.35924553422223,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 27,
                            ActivityPattern = 2,
                            AnimalCategoryId = 2,
                            Arise = new TimeSpan(53099359466),
                            BedTime = new TimeSpan(523820289439),
                            DietaryClass = 3,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(19547945613),
                            Name = "Paula",
                            Prey = "Wolf",
                            SecurityRequirement = 1,
                            Size = 6,
                            SpaceRequirement = 451.99132277257337,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 28,
                            ActivityPattern = 1,
                            AnimalCategoryId = 7,
                            Arise = new TimeSpan(129353015904),
                            BedTime = new TimeSpan(628046762547),
                            DietaryClass = 1,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(61647658440),
                            Name = "Gayle",
                            Prey = "Zebra",
                            SecurityRequirement = 1,
                            Size = 4,
                            SpaceRequirement = 443.87651552626699,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 29,
                            ActivityPattern = 2,
                            AnimalCategoryId = 3,
                            Arise = new TimeSpan(194868312356),
                            BedTime = new TimeSpan(179691622088),
                            DietaryClass = 3,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(62727033797),
                            Name = "Mireille",
                            Prey = "Eagle",
                            SecurityRequirement = 3,
                            Size = 6,
                            SpaceRequirement = 360.46767217594561,
                            Species = "Shark",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 30,
                            ActivityPattern = 3,
                            AnimalCategoryId = 4,
                            Arise = new TimeSpan(76969667843),
                            BedTime = new TimeSpan(720225221839),
                            DietaryClass = 3,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(36771497375),
                            Name = "Virginie",
                            Prey = "Zebra",
                            SecurityRequirement = 1,
                            Size = 3,
                            SpaceRequirement = 179.08981631933236,
                            Species = "Eagle",
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.AnimalCategory", b =>
                {
                    b.Property<int>("AnimalCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalCategoryId");

                    b.ToTable("AnimalCategories");

                    b.HasData(
                        new
                        {
                            AnimalCategoryId = 1,
                            Name = "Birds"
                        },
                        new
                        {
                            AnimalCategoryId = 2,
                            Name = "Arachnids"
                        },
                        new
                        {
                            AnimalCategoryId = 3,
                            Name = "Birds"
                        },
                        new
                        {
                            AnimalCategoryId = 4,
                            Name = "Arachnids"
                        },
                        new
                        {
                            AnimalCategoryId = 5,
                            Name = "Birds"
                        },
                        new
                        {
                            AnimalCategoryId = 6,
                            Name = "Arachnids"
                        },
                        new
                        {
                            AnimalCategoryId = 7,
                            Name = "Insects"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnclosureId"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            Climate = 1,
                            Habitat = 8,
                            Name = "Grayson",
                            SecurityLevel = 2,
                            Size = 448.99073820514172,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 2,
                            Climate = 2,
                            Habitat = 4,
                            Name = "Uriah",
                            SecurityLevel = 1,
                            Size = 405.91602617218905,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 3,
                            Climate = 3,
                            Habitat = 2,
                            Name = "Hayley",
                            SecurityLevel = 3,
                            Size = 435.78062550433941,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 4,
                            Climate = 1,
                            Habitat = 0,
                            Name = "Marty",
                            SecurityLevel = 1,
                            Size = 296.87672797910722,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 5,
                            Climate = 2,
                            Habitat = 0,
                            Name = "Orpha",
                            SecurityLevel = 2,
                            Size = 300.83291497120302,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 6,
                            Climate = 1,
                            Habitat = 1,
                            Name = "Cristian",
                            SecurityLevel = 3,
                            Size = 443.15214740259211,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Property<int>("ZooId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZooId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZooId");

                    b.ToTable("Zoos");

                    b.HasData(
                        new
                        {
                            ZooId = 1,
                            Name = "Tremblay - Hamill"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.AnimalCategory", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dierentuin_eindopdracht.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Enclosure");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.AnimalCategory", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
