// <auto-generated />
using System;
using Dierentuin_eindopdracht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dierentuin_eindopdracht.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20250219163802_NewStart")]
    partial class NewStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Arise")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BedTime")
                        .HasColumnType("time");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FeedingTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirment")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(47314443712),
                            BedTime = new TimeSpan(275482728665),
                            CategoryId = 5,
                            DietaryClass = 5,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(54843076852),
                            Name = "Hattie",
                            Prey = "Lion",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 387.23341698203183,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(178738956670),
                            BedTime = new TimeSpan(268858208707),
                            CategoryId = 5,
                            DietaryClass = 2,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(41722100711),
                            Name = "Idella",
                            Prey = "Penguin",
                            SecurityRequirment = 1,
                            Size = 4,
                            SpaceRequirement = 495.52163265420398,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 3,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(46125502544),
                            BedTime = new TimeSpan(272432288544),
                            CategoryId = 5,
                            DietaryClass = 5,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(51777067818),
                            Name = "Liza",
                            Prey = "Lion",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 357.39589480402924,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 4,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(139845612075),
                            BedTime = new TimeSpan(209381115322),
                            CategoryId = 5,
                            DietaryClass = 5,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(30258155207),
                            Name = "Maurice",
                            Prey = "Penguin",
                            SecurityRequirment = 2,
                            Size = 5,
                            SpaceRequirement = 149.7243389014221,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 5,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(183378337156),
                            BedTime = new TimeSpan(606897816802),
                            CategoryId = 1,
                            DietaryClass = 2,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(64852849105),
                            Name = "Richie",
                            Prey = "Tiger",
                            SecurityRequirment = 3,
                            Size = 2,
                            SpaceRequirement = 48.504286897227352,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 6,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(185047792117),
                            BedTime = new TimeSpan(401790895226),
                            CategoryId = 3,
                            DietaryClass = 5,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(13450433904),
                            Name = "Buck",
                            Prey = "Lion",
                            SecurityRequirment = 3,
                            Size = 3,
                            SpaceRequirement = 244.33639718905684,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 7,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(199697444227),
                            BedTime = new TimeSpan(776823335418),
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(52774688983),
                            Name = "Cade",
                            Prey = "Tiger",
                            SecurityRequirment = 1,
                            Size = 6,
                            SpaceRequirement = 382.72789653954305,
                            Species = "Giraffe",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 8,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(94685397162),
                            BedTime = new TimeSpan(287533875186),
                            CategoryId = 5,
                            DietaryClass = 5,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(66128477796),
                            Name = "Lizzie",
                            Prey = "Giraffe",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 16.015820295910981,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 9,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(201598183116),
                            BedTime = new TimeSpan(476027202125),
                            CategoryId = 4,
                            DietaryClass = 4,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(21147670512),
                            Name = "May",
                            Prey = "Elephant",
                            SecurityRequirment = 3,
                            Size = 5,
                            SpaceRequirement = 180.60968908315795,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 10,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(133759977685),
                            BedTime = new TimeSpan(107261277721),
                            CategoryId = 2,
                            DietaryClass = 5,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(67289902542),
                            Name = "Don",
                            Prey = "Penguin",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 239.06306665958337,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 11,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(144098375657),
                            BedTime = new TimeSpan(657971483613),
                            CategoryId = 3,
                            DietaryClass = 4,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(45984647751),
                            Name = "Laurianne",
                            Prey = "Elephant",
                            SecurityRequirment = 2,
                            Size = 5,
                            SpaceRequirement = 429.67011478053092,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 12,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(75011657048),
                            BedTime = new TimeSpan(572312848364),
                            CategoryId = 5,
                            DietaryClass = 5,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(30274135927),
                            Name = "Lauretta",
                            Prey = "Elephant",
                            SecurityRequirment = 2,
                            Size = 4,
                            SpaceRequirement = 248.51109664917183,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 13,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(26660064931),
                            BedTime = new TimeSpan(434168964258),
                            CategoryId = 1,
                            DietaryClass = 2,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(43651018392),
                            Name = "Aurelio",
                            Prey = "Tiger",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 114.04001765193084,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 14,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(7035749112),
                            BedTime = new TimeSpan(117790016682),
                            CategoryId = 3,
                            DietaryClass = 3,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(40997552952),
                            Name = "Donato",
                            Prey = "Penguin",
                            SecurityRequirment = 2,
                            Size = 4,
                            SpaceRequirement = 147.11069506749681,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 15,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(47765150544),
                            BedTime = new TimeSpan(7083953155),
                            CategoryId = 3,
                            DietaryClass = 1,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(23979544026),
                            Name = "Reece",
                            Prey = "Elephant",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 78.39218871021373,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 16,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(204207458821),
                            BedTime = new TimeSpan(19522794249),
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(19306960545),
                            Name = "Mariana",
                            Prey = "Tiger",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 87.316844657781616,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 17,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(172575835538),
                            BedTime = new TimeSpan(595460353567),
                            CategoryId = 5,
                            DietaryClass = 4,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(42946154529),
                            Name = "Kiel",
                            Prey = "Penguin",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 434.47274809660837,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 18,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(57182537585),
                            BedTime = new TimeSpan(492526206177),
                            CategoryId = 5,
                            DietaryClass = 1,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(30378208429),
                            Name = "Jedidiah",
                            Prey = "Penguin",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 396.23434305356307,
                            Species = "Penguin",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 19,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(58229305341),
                            BedTime = new TimeSpan(437213422470),
                            CategoryId = 4,
                            DietaryClass = 4,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(5714525601),
                            Name = "Golden",
                            Prey = "Elephant",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 59.417505129701553,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 20,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(37945734298),
                            BedTime = new TimeSpan(394245190856),
                            CategoryId = 4,
                            DietaryClass = 5,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(50137239445),
                            Name = "Willa",
                            Prey = "Giraffe",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 19.217550991013653,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 21,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(7917982568),
                            BedTime = new TimeSpan(269286848531),
                            CategoryId = 3,
                            DietaryClass = 2,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(17782663723),
                            Name = "Simeon",
                            Prey = "Giraffe",
                            SecurityRequirment = 3,
                            Size = 2,
                            SpaceRequirement = 415.08112566132615,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 22,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(154418060060),
                            BedTime = new TimeSpan(576609208502),
                            CategoryId = 1,
                            DietaryClass = 4,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(43630863403),
                            Name = "Odell",
                            Prey = "Giraffe",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 446.25900703567845,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 23,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(144248523062),
                            BedTime = new TimeSpan(187234051384),
                            CategoryId = 3,
                            DietaryClass = 4,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(45655050724),
                            Name = "Makayla",
                            Prey = "Elephant",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 80.084243130882811,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 24,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(58198134314),
                            BedTime = new TimeSpan(168036387456),
                            CategoryId = 3,
                            DietaryClass = 1,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(49615524561),
                            Name = "Emiliano",
                            Prey = "Tiger",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 353.09382913789835,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 25,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(166344798044),
                            BedTime = new TimeSpan(450725749334),
                            CategoryId = 3,
                            DietaryClass = 5,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(69798229360),
                            Name = "Jovanny",
                            Prey = "Giraffe",
                            SecurityRequirment = 1,
                            Size = 4,
                            SpaceRequirement = 262.58858107410492,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 26,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(54669294918),
                            BedTime = new TimeSpan(542504046106),
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(61677456327),
                            Name = "Gunner",
                            Prey = "Penguin",
                            SecurityRequirment = 1,
                            Size = 4,
                            SpaceRequirement = 461.32822953275718,
                            Species = "Giraffe",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 27,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(68983715406),
                            BedTime = new TimeSpan(260382031383),
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(37322565542),
                            Name = "Katherine",
                            Prey = "Penguin",
                            SecurityRequirment = 2,
                            Size = 4,
                            SpaceRequirement = 364.08086782810994,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 28,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(8079244242),
                            BedTime = new TimeSpan(67335219099),
                            CategoryId = 2,
                            DietaryClass = 4,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(40241331823),
                            Name = "Brigitte",
                            Prey = "Elephant",
                            SecurityRequirment = 3,
                            Size = 5,
                            SpaceRequirement = 357.41735660029195,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 29,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(74832041473),
                            BedTime = new TimeSpan(471025959801),
                            CategoryId = 2,
                            DietaryClass = 5,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(35992052659),
                            Name = "Domenica",
                            Prey = "Elephant",
                            SecurityRequirment = 3,
                            Size = 6,
                            SpaceRequirement = 27.850196066951142,
                            Species = "Lion",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 30,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(112422616530),
                            BedTime = new TimeSpan(39739689031),
                            CategoryId = 5,
                            DietaryClass = 4,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(8500789948),
                            Name = "Skylar",
                            Prey = "Giraffe",
                            SecurityRequirment = 2,
                            Size = 2,
                            SpaceRequirement = 295.08229847584334,
                            Species = "Tiger",
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fishes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Mammals"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Mammals"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnclosureId"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            Climate = 3,
                            Habitat = 4,
                            Name = "iusto",
                            SecurityLevel = 2,
                            Size = 628.25270603018873,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 2,
                            Climate = 1,
                            Habitat = 1,
                            Name = "nulla",
                            SecurityLevel = 1,
                            Size = 409.33744118448237,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 3,
                            Climate = 3,
                            Habitat = 8,
                            Name = "odio",
                            SecurityLevel = 1,
                            Size = 834.97963382873229,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 4,
                            Climate = 3,
                            Habitat = 0,
                            Name = "est",
                            SecurityLevel = 1,
                            Size = 756.2794256963673,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 5,
                            Climate = 2,
                            Habitat = 0,
                            Name = "ducimus",
                            SecurityLevel = 3,
                            Size = 168.89336363545044,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 6,
                            Climate = 2,
                            Habitat = 4,
                            Name = "voluptas",
                            SecurityLevel = 1,
                            Size = 456.43705507639908,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Property<int>("ZooId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZooId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZooId");

                    b.ToTable("Zoos");

                    b.HasData(
                        new
                        {
                            ZooId = 1,
                            Name = "Schmidt LLC"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Dierentuin_eindopdracht.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Enclosure");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
