// <auto-generated />
using System;
using Dierentuin_eindopdracht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dierentuin_eindopdracht.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Arise")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BedTime")
                        .HasColumnType("time");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FeedingTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirment")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(200182117564),
                            BedTime = new TimeSpan(180134109493),
                            CategoryId = 2,
                            DietaryClass = 5,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(65419847840),
                            Name = "Haskell",
                            Prey = "molestiae",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 383.64650105176895,
                            Species = "Cobra",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(30770450166),
                            BedTime = new TimeSpan(702996273597),
                            CategoryId = 7,
                            DietaryClass = 4,
                            EnclosureId = 15,
                            FeedingTime = new TimeSpan(65114320001),
                            Name = "Napoleon",
                            Prey = "qui",
                            SecurityRequirment = 1,
                            Size = 6,
                            SpaceRequirement = 22.097264367573192,
                            Species = "Penguin",
                            ZooId = 9
                        },
                        new
                        {
                            AnimalId = 3,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(114824357390),
                            BedTime = new TimeSpan(42999096052),
                            CategoryId = 10,
                            DietaryClass = 5,
                            EnclosureId = 12,
                            FeedingTime = new TimeSpan(2187147807),
                            Name = "Florence",
                            Prey = "dolorem",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 133.82022730882255,
                            Species = "Cobra",
                            ZooId = 8
                        },
                        new
                        {
                            AnimalId = 4,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(9411394552),
                            BedTime = new TimeSpan(352522665957),
                            CategoryId = 6,
                            DietaryClass = 1,
                            EnclosureId = 12,
                            FeedingTime = new TimeSpan(29371363492),
                            Name = "Laney",
                            Prey = "quisquam",
                            SecurityRequirment = 2,
                            Size = 2,
                            SpaceRequirement = 203.29529276968219,
                            Species = "Elephant",
                            ZooId = 8
                        },
                        new
                        {
                            AnimalId = 5,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(129344489563),
                            BedTime = new TimeSpan(91143972258),
                            CategoryId = 6,
                            DietaryClass = 1,
                            EnclosureId = 10,
                            FeedingTime = new TimeSpan(15055524243),
                            Name = "Agustin",
                            Prey = "exercitationem",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 258.36142983133698,
                            Species = "Cobra",
                            ZooId = 2
                        },
                        new
                        {
                            AnimalId = 6,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(185616332717),
                            BedTime = new TimeSpan(778149941284),
                            CategoryId = 9,
                            DietaryClass = 3,
                            EnclosureId = 8,
                            FeedingTime = new TimeSpan(71030031877),
                            Name = "Gloria",
                            Prey = "inventore",
                            SecurityRequirment = 3,
                            Size = 3,
                            SpaceRequirement = 204.69066170591807,
                            Species = "Eagle",
                            ZooId = 6
                        },
                        new
                        {
                            AnimalId = 7,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(37608962192),
                            BedTime = new TimeSpan(1126861525),
                            CategoryId = 6,
                            DietaryClass = 4,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(52381060166),
                            Name = "Pat",
                            Prey = "itaque",
                            SecurityRequirment = 3,
                            Size = 4,
                            SpaceRequirement = 408.0739910357554,
                            Species = "Cobra",
                            ZooId = 7
                        },
                        new
                        {
                            AnimalId = 8,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(51088790664),
                            BedTime = new TimeSpan(471568893951),
                            CategoryId = 10,
                            DietaryClass = 1,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(66145423250),
                            Name = "Shawn",
                            Prey = "ea",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 476.53984298867175,
                            Species = "Kangaroo",
                            ZooId = 3
                        },
                        new
                        {
                            AnimalId = 9,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(49927774862),
                            BedTime = new TimeSpan(315606380705),
                            CategoryId = 4,
                            DietaryClass = 1,
                            EnclosureId = 10,
                            FeedingTime = new TimeSpan(3761946948),
                            Name = "Megane",
                            Prey = "et",
                            SecurityRequirment = 2,
                            Size = 6,
                            SpaceRequirement = 224.84113573862194,
                            Species = "Giraffe",
                            ZooId = 2
                        },
                        new
                        {
                            AnimalId = 10,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(102305893360),
                            BedTime = new TimeSpan(357165791407),
                            CategoryId = 8,
                            DietaryClass = 1,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(27018965239),
                            Name = "Shanie",
                            Prey = "deleniti",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 265.78961992673158,
                            Species = "Tiger",
                            ZooId = 5
                        },
                        new
                        {
                            AnimalId = 11,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(86339881114),
                            BedTime = new TimeSpan(172624076788),
                            CategoryId = 9,
                            DietaryClass = 1,
                            EnclosureId = 13,
                            FeedingTime = new TimeSpan(2767007975),
                            Name = "Jevon",
                            Prey = "error",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 163.42002381097569,
                            Species = "Eagle",
                            ZooId = 5
                        },
                        new
                        {
                            AnimalId = 12,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(206375178726),
                            BedTime = new TimeSpan(463919143154),
                            CategoryId = 4,
                            DietaryClass = 1,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(50435853913),
                            Name = "Darren",
                            Prey = "quod",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 375.32974812733983,
                            Species = "Tiger",
                            ZooId = 6
                        },
                        new
                        {
                            AnimalId = 13,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(63805689537),
                            BedTime = new TimeSpan(73327467480),
                            CategoryId = 10,
                            DietaryClass = 5,
                            EnclosureId = 11,
                            FeedingTime = new TimeSpan(16050594094),
                            Name = "Brett",
                            Prey = "eaque",
                            SecurityRequirment = 2,
                            Size = 5,
                            SpaceRequirement = 328.71988496632446,
                            Species = "Tiger",
                            ZooId = 9
                        },
                        new
                        {
                            AnimalId = 14,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(143026735044),
                            BedTime = new TimeSpan(791748368447),
                            CategoryId = 1,
                            DietaryClass = 4,
                            EnclosureId = 11,
                            FeedingTime = new TimeSpan(57009691717),
                            Name = "Magdalen",
                            Prey = "quam",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 256.39396598380802,
                            Species = "Giraffe",
                            ZooId = 9
                        },
                        new
                        {
                            AnimalId = 15,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(90892765741),
                            BedTime = new TimeSpan(338366204843),
                            CategoryId = 10,
                            DietaryClass = 3,
                            EnclosureId = 10,
                            FeedingTime = new TimeSpan(951797193),
                            Name = "Darian",
                            Prey = "unde",
                            SecurityRequirment = 1,
                            Size = 2,
                            SpaceRequirement = 37.752579420392628,
                            Species = "Lion",
                            ZooId = 2
                        },
                        new
                        {
                            AnimalId = 16,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(20690538026),
                            BedTime = new TimeSpan(171642347196),
                            CategoryId = 10,
                            DietaryClass = 1,
                            EnclosureId = 16,
                            FeedingTime = new TimeSpan(4740869519),
                            Name = "Bobby",
                            Prey = "dicta",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 146.56541220762855,
                            Species = "Kangaroo",
                            ZooId = 10
                        },
                        new
                        {
                            AnimalId = 17,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(55310785922),
                            BedTime = new TimeSpan(528003652134),
                            CategoryId = 1,
                            DietaryClass = 3,
                            EnclosureId = 16,
                            FeedingTime = new TimeSpan(826441911),
                            Name = "Harmony",
                            Prey = "consequatur",
                            SecurityRequirment = 3,
                            Size = 2,
                            SpaceRequirement = 475.4036827887067,
                            Species = "Penguin",
                            ZooId = 10
                        },
                        new
                        {
                            AnimalId = 18,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(42785905863),
                            BedTime = new TimeSpan(490876910815),
                            CategoryId = 10,
                            DietaryClass = 5,
                            EnclosureId = 17,
                            FeedingTime = new TimeSpan(67225248168),
                            Name = "Sanford",
                            Prey = "voluptates",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 259.71422645809389,
                            Species = "Penguin",
                            ZooId = 3
                        },
                        new
                        {
                            AnimalId = 19,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(105482106215),
                            BedTime = new TimeSpan(123803231473),
                            CategoryId = 3,
                            DietaryClass = 3,
                            EnclosureId = 18,
                            FeedingTime = new TimeSpan(65940316022),
                            Name = "Gardner",
                            Prey = "atque",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 424.52544162174394,
                            Species = "Tiger",
                            ZooId = 4
                        },
                        new
                        {
                            AnimalId = 20,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(159880392291),
                            BedTime = new TimeSpan(39336319536),
                            CategoryId = 10,
                            DietaryClass = 2,
                            EnclosureId = 13,
                            FeedingTime = new TimeSpan(20879802473),
                            Name = "Beverly",
                            Prey = "nostrum",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 126.88994844327411,
                            Species = "Eagle",
                            ZooId = 5
                        },
                        new
                        {
                            AnimalId = 21,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(43574232937),
                            BedTime = new TimeSpan(709298708327),
                            CategoryId = 9,
                            DietaryClass = 1,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(35179616456),
                            Name = "Lorena",
                            Prey = "incidunt",
                            SecurityRequirment = 3,
                            Size = 4,
                            SpaceRequirement = 270.46576953766595,
                            Species = "Elephant",
                            ZooId = 6
                        },
                        new
                        {
                            AnimalId = 22,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(215221750472),
                            BedTime = new TimeSpan(200883400486),
                            CategoryId = 4,
                            DietaryClass = 1,
                            EnclosureId = 17,
                            FeedingTime = new TimeSpan(44957298282),
                            Name = "Destiney",
                            Prey = "aliquam",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 186.83332152101229,
                            Species = "Penguin",
                            ZooId = 3
                        },
                        new
                        {
                            AnimalId = 23,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(98177557130),
                            BedTime = new TimeSpan(557794717621),
                            CategoryId = 9,
                            DietaryClass = 1,
                            EnclosureId = 12,
                            FeedingTime = new TimeSpan(58468578182),
                            Name = "Filomena",
                            Prey = "voluptate",
                            SecurityRequirment = 2,
                            Size = 4,
                            SpaceRequirement = 430.71728434603796,
                            Species = "Giraffe",
                            ZooId = 8
                        },
                        new
                        {
                            AnimalId = 24,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(123163444320),
                            BedTime = new TimeSpan(606539646354),
                            CategoryId = 6,
                            DietaryClass = 2,
                            EnclosureId = 18,
                            FeedingTime = new TimeSpan(68912346884),
                            Name = "Laurence",
                            Prey = "cupiditate",
                            SecurityRequirment = 3,
                            Size = 2,
                            SpaceRequirement = 108.9350280396493,
                            Species = "Giraffe",
                            ZooId = 4
                        },
                        new
                        {
                            AnimalId = 25,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(45769239572),
                            BedTime = new TimeSpan(388674793193),
                            CategoryId = 9,
                            DietaryClass = 5,
                            EnclosureId = 18,
                            FeedingTime = new TimeSpan(5188010079),
                            Name = "Gudrun",
                            Prey = "a",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 218.59651636887003,
                            Species = "Elephant",
                            ZooId = 4
                        },
                        new
                        {
                            AnimalId = 26,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(53483630095),
                            BedTime = new TimeSpan(734370920941),
                            CategoryId = 5,
                            DietaryClass = 1,
                            EnclosureId = 7,
                            FeedingTime = new TimeSpan(70219854812),
                            Name = "Ila",
                            Prey = "magnam",
                            SecurityRequirment = 1,
                            Size = 6,
                            SpaceRequirement = 310.95643452331751,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 27,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(119109704261),
                            BedTime = new TimeSpan(261642441290),
                            CategoryId = 4,
                            DietaryClass = 3,
                            EnclosureId = 10,
                            FeedingTime = new TimeSpan(29715681460),
                            Name = "Arnulfo",
                            Prey = "dolor",
                            SecurityRequirment = 3,
                            Size = 5,
                            SpaceRequirement = 376.32084913156433,
                            Species = "Kangaroo",
                            ZooId = 2
                        },
                        new
                        {
                            AnimalId = 28,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(171693329341),
                            BedTime = new TimeSpan(441806220870),
                            CategoryId = 2,
                            DietaryClass = 2,
                            EnclosureId = 2,
                            FeedingTime = new TimeSpan(11649506346),
                            Name = "Jayden",
                            Prey = "error",
                            SecurityRequirment = 2,
                            Size = 1,
                            SpaceRequirement = 313.60364071726309,
                            Species = "Kangaroo",
                            ZooId = 10
                        },
                        new
                        {
                            AnimalId = 29,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(83722830140),
                            BedTime = new TimeSpan(435920578944),
                            CategoryId = 10,
                            DietaryClass = 5,
                            EnclosureId = 3,
                            FeedingTime = new TimeSpan(16892794642),
                            Name = "Narciso",
                            Prey = "cupiditate",
                            SecurityRequirment = 2,
                            Size = 4,
                            SpaceRequirement = 357.77020725318874,
                            Species = "Kangaroo",
                            ZooId = 6
                        },
                        new
                        {
                            AnimalId = 30,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(174724969900),
                            BedTime = new TimeSpan(246383150711),
                            CategoryId = 7,
                            DietaryClass = 2,
                            EnclosureId = 15,
                            FeedingTime = new TimeSpan(33177743172),
                            Name = "Lindsey",
                            Prey = "eos",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 365.20880730098639,
                            Species = "Tiger",
                            ZooId = 9
                        },
                        new
                        {
                            AnimalId = 31,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(48755860198),
                            BedTime = new TimeSpan(655077982563),
                            CategoryId = 6,
                            DietaryClass = 4,
                            EnclosureId = 20,
                            FeedingTime = new TimeSpan(10546947560),
                            Name = "Giovanni",
                            Prey = "ipsum",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 249.31260418648941,
                            Species = "Lion",
                            ZooId = 7
                        },
                        new
                        {
                            AnimalId = 32,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(194724353584),
                            BedTime = new TimeSpan(548134681639),
                            CategoryId = 4,
                            DietaryClass = 5,
                            EnclosureId = 9,
                            FeedingTime = new TimeSpan(61522221875),
                            Name = "Cloyd",
                            Prey = "doloribus",
                            SecurityRequirment = 3,
                            Size = 3,
                            SpaceRequirement = 126.31452210258149,
                            Species = "Eagle",
                            ZooId = 8
                        },
                        new
                        {
                            AnimalId = 33,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(186247866723),
                            BedTime = new TimeSpan(543820685846),
                            CategoryId = 8,
                            DietaryClass = 5,
                            EnclosureId = 14,
                            FeedingTime = new TimeSpan(65300212895),
                            Name = "Kacey",
                            Prey = "et",
                            SecurityRequirment = 1,
                            Size = 5,
                            SpaceRequirement = 244.03192208913978,
                            Species = "Cobra",
                            ZooId = 4
                        },
                        new
                        {
                            AnimalId = 34,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(175252969422),
                            BedTime = new TimeSpan(320757952344),
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(43016414103),
                            Name = "Raoul",
                            Prey = "eveniet",
                            SecurityRequirment = 1,
                            Size = 4,
                            SpaceRequirement = 51.282438211561768,
                            Species = "Elephant",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 35,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(81568062641),
                            BedTime = new TimeSpan(417909047382),
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 5,
                            FeedingTime = new TimeSpan(37286821155),
                            Name = "Veronica",
                            Prey = "velit",
                            SecurityRequirment = 2,
                            Size = 5,
                            SpaceRequirement = 368.72069285413545,
                            Species = "Lion",
                            ZooId = 3
                        },
                        new
                        {
                            AnimalId = 36,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(173014615829),
                            BedTime = new TimeSpan(784968044652),
                            CategoryId = 10,
                            DietaryClass = 4,
                            EnclosureId = 20,
                            FeedingTime = new TimeSpan(66494871645),
                            Name = "Neha",
                            Prey = "deleniti",
                            SecurityRequirment = 2,
                            Size = 3,
                            SpaceRequirement = 436.88073782486828,
                            Species = "Giraffe",
                            ZooId = 7
                        },
                        new
                        {
                            AnimalId = 37,
                            ActivityPattern = 2,
                            Arise = new TimeSpan(92290680294),
                            BedTime = new TimeSpan(522631708894),
                            CategoryId = 6,
                            DietaryClass = 2,
                            EnclosureId = 6,
                            FeedingTime = new TimeSpan(5717250249),
                            Name = "Everette",
                            Prey = "voluptas",
                            SecurityRequirment = 1,
                            Size = 1,
                            SpaceRequirement = 35.719409087700683,
                            Species = "Tiger",
                            ZooId = 1
                        },
                        new
                        {
                            AnimalId = 38,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(94567393191),
                            BedTime = new TimeSpan(350818464663),
                            CategoryId = 4,
                            DietaryClass = 3,
                            EnclosureId = 16,
                            FeedingTime = new TimeSpan(33840276266),
                            Name = "Verner",
                            Prey = "consequuntur",
                            SecurityRequirment = 3,
                            Size = 1,
                            SpaceRequirement = 371.59520378102928,
                            Species = "Lion",
                            ZooId = 10
                        },
                        new
                        {
                            AnimalId = 39,
                            ActivityPattern = 3,
                            Arise = new TimeSpan(201977096799),
                            BedTime = new TimeSpan(291685372864),
                            CategoryId = 8,
                            DietaryClass = 3,
                            EnclosureId = 4,
                            FeedingTime = new TimeSpan(68023053884),
                            Name = "Roselyn",
                            Prey = "harum",
                            SecurityRequirment = 3,
                            Size = 2,
                            SpaceRequirement = 496.74224711467923,
                            Species = "Tiger",
                            ZooId = 7
                        },
                        new
                        {
                            AnimalId = 40,
                            ActivityPattern = 1,
                            Arise = new TimeSpan(108978151391),
                            BedTime = new TimeSpan(151455119141),
                            CategoryId = 2,
                            DietaryClass = 2,
                            EnclosureId = 1,
                            FeedingTime = new TimeSpan(30434117702),
                            Name = "Rosie",
                            Prey = "optio",
                            SecurityRequirment = 1,
                            Size = 3,
                            SpaceRequirement = 324.7553732256186,
                            Species = "Eagle",
                            ZooId = 5
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Insects"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Mammals"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Mammals"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Fishes"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Mammals"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Birds"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Birds"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Reptiles"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnclosureId"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosure");

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            Climate = 3,
                            Habitat = 0,
                            Name = "unde",
                            SecurityLevel = 3,
                            Size = 841.64121757243811,
                            ZooId = 5
                        },
                        new
                        {
                            EnclosureId = 2,
                            Climate = 2,
                            Habitat = 0,
                            Name = "et",
                            SecurityLevel = 3,
                            Size = 977.52249437821297,
                            ZooId = 10
                        },
                        new
                        {
                            EnclosureId = 3,
                            Climate = 3,
                            Habitat = 0,
                            Name = "optio",
                            SecurityLevel = 1,
                            Size = 527.51308609716352,
                            ZooId = 6
                        },
                        new
                        {
                            EnclosureId = 4,
                            Climate = 2,
                            Habitat = 4,
                            Name = "modi",
                            SecurityLevel = 1,
                            Size = 902.38447889501424,
                            ZooId = 7
                        },
                        new
                        {
                            EnclosureId = 5,
                            Climate = 1,
                            Habitat = 4,
                            Name = "modi",
                            SecurityLevel = 2,
                            Size = 578.63162132052707,
                            ZooId = 3
                        },
                        new
                        {
                            EnclosureId = 6,
                            Climate = 1,
                            Habitat = 1,
                            Name = "rerum",
                            SecurityLevel = 2,
                            Size = 826.26411276455883,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 7,
                            Climate = 2,
                            Habitat = 2,
                            Name = "nisi",
                            SecurityLevel = 1,
                            Size = 213.62112745019482,
                            ZooId = 1
                        },
                        new
                        {
                            EnclosureId = 8,
                            Climate = 2,
                            Habitat = 1,
                            Name = "nihil",
                            SecurityLevel = 3,
                            Size = 124.29017987195763,
                            ZooId = 6
                        },
                        new
                        {
                            EnclosureId = 9,
                            Climate = 3,
                            Habitat = 2,
                            Name = "cum",
                            SecurityLevel = 1,
                            Size = 616.08083770531709,
                            ZooId = 8
                        },
                        new
                        {
                            EnclosureId = 10,
                            Climate = 1,
                            Habitat = 2,
                            Name = "voluptatem",
                            SecurityLevel = 3,
                            Size = 901.72938789632553,
                            ZooId = 2
                        },
                        new
                        {
                            EnclosureId = 11,
                            Climate = 3,
                            Habitat = 2,
                            Name = "dolores",
                            SecurityLevel = 1,
                            Size = 225.43836920483369,
                            ZooId = 9
                        },
                        new
                        {
                            EnclosureId = 12,
                            Climate = 1,
                            Habitat = 1,
                            Name = "sapiente",
                            SecurityLevel = 1,
                            Size = 486.62615349070711,
                            ZooId = 8
                        },
                        new
                        {
                            EnclosureId = 13,
                            Climate = 3,
                            Habitat = 1,
                            Name = "ex",
                            SecurityLevel = 3,
                            Size = 422.05543959402422,
                            ZooId = 5
                        },
                        new
                        {
                            EnclosureId = 14,
                            Climate = 1,
                            Habitat = 4,
                            Name = "ducimus",
                            SecurityLevel = 2,
                            Size = 319.71051684332508,
                            ZooId = 4
                        },
                        new
                        {
                            EnclosureId = 15,
                            Climate = 2,
                            Habitat = 4,
                            Name = "corporis",
                            SecurityLevel = 3,
                            Size = 401.47874081875432,
                            ZooId = 9
                        },
                        new
                        {
                            EnclosureId = 16,
                            Climate = 1,
                            Habitat = 0,
                            Name = "consequuntur",
                            SecurityLevel = 1,
                            Size = 892.9487193195622,
                            ZooId = 10
                        },
                        new
                        {
                            EnclosureId = 17,
                            Climate = 3,
                            Habitat = 2,
                            Name = "id",
                            SecurityLevel = 2,
                            Size = 867.91827158256206,
                            ZooId = 3
                        },
                        new
                        {
                            EnclosureId = 18,
                            Climate = 2,
                            Habitat = 4,
                            Name = "qui",
                            SecurityLevel = 1,
                            Size = 810.9944796860035,
                            ZooId = 4
                        },
                        new
                        {
                            EnclosureId = 19,
                            Climate = 2,
                            Habitat = 0,
                            Name = "velit",
                            SecurityLevel = 3,
                            Size = 937.82436519726764,
                            ZooId = 2
                        },
                        new
                        {
                            EnclosureId = 20,
                            Climate = 3,
                            Habitat = 4,
                            Name = "alias",
                            SecurityLevel = 1,
                            Size = 207.36464978763058,
                            ZooId = 7
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Property<int>("ZooId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZooId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZooId");

                    b.ToTable("Zoo");

                    b.HasData(
                        new
                        {
                            ZooId = 1,
                            Name = "Jeramie Metz"
                        },
                        new
                        {
                            ZooId = 2,
                            Name = "Jeffrey Wunsch"
                        },
                        new
                        {
                            ZooId = 3,
                            Name = "Norwood Rowe"
                        },
                        new
                        {
                            ZooId = 4,
                            Name = "Howard Rempel"
                        },
                        new
                        {
                            ZooId = 5,
                            Name = "Macey Kub"
                        },
                        new
                        {
                            ZooId = 6,
                            Name = "Amber Zemlak"
                        },
                        new
                        {
                            ZooId = 7,
                            Name = "Devan Farrell"
                        },
                        new
                        {
                            ZooId = 8,
                            Name = "Judy Runolfsson"
                        },
                        new
                        {
                            ZooId = 9,
                            Name = "Dariana Langosh"
                        },
                        new
                        {
                            ZooId = 10,
                            Name = "Rowan O'Hara"
                        });
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Animal", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Dierentuin_eindopdracht.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Enclosure");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.HasOne("Dierentuin_eindopdracht.Models.Zoo", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin_eindopdracht.Models.Zoo", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
